############# Russian navigation ##############

# main menu
[[main]]
name = "Главная"
pageRef = "/"
weight = 1

[[main]]
weight = 2
name = "Блог"
pageRef = "/blog"

[[main]]
weight = 3
name = "База данных"
pageRef = "/fishbase"

[[main]]
name = "Обо мне"
pageRef = "/about"
weight = 4

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "Обо мне"
pageRef = "/about"
weight = 1

[[footer]]
name = "Блог"
pageRef = "/blog"
weight = 2

[[footer]]
name = "База данных"
pageRef = "/fishbase"
weight = 3
