############# Russian navigation ##############

# main menu
[[main]]
name = "Главная"
pageRef = "/"
weight = 1

[[main]]
weight = 2
name = "Блог"
pageRef = "/blog"

[[main]]
weight = 3
name = "База данных"
pageRef = "/database"

[[main]]

[[main]]
name = "Обо мне"
pageRef = "/about"
weight = 4

# footer menu
[[footer]]
name = "Обо мне"
pageRef = "/about"
weight = 1

[[footer]]
weight = 2
name = "Блог"
pageRef = "/blog"

[[footer]]
weight = 3
name = "База данных"
pageRef = "/database"

[[footer]]
weight = 4
name = "Категории"
pageRef = "/categories"

[[footer]]
weight = 5
name = "Теги"
pageRef = "/tags"
