############# Russian navigation ##############

# main menu
[[main]]
name = "Главная"
pageRef = "/"
weight = 1

[[main]]
weight = 2
name = "Блог"
pageRef = "/blog"

[[main]]
weight = 3
name = "База данных"
pageRef = "/fishbase"

[[main]]
name = "Обо мне"
pageRef = "/about"
weight = 4

# footer menu
[[footer]]
name = "Обо мне"
pageRef = "/about"
weight = 1

[[footer]]
name = "Блог"
pageRef = "/blog"
weight = 2

[[footer]]
name = "База данных"
pageRef = "/fishbase"
weight = 3
